run:
  deadline: 5m
  skip-files: [ ]
  skip-dirs: [ "maybe_later", "cmd" ]

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 20
  maligned:
    suggest-new: true
  goconst:
    min-len: 5
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 62
  godox:
    keywords:
      - FIXME
  gofumpt:
    extra-rules: true
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/sirupsen/logrus
      - github.com/pkg/errors
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - sloppyReassign
      - rangeValCopy
      - octalLiteral
      - paramTypeCombine # already handle by gofumpt.extra-rules
      - unnamedResult
    settings:
      hugeParam:
        sizeThreshold: 100

linters:
  enable-all: true
  disable:
    - maligned # deprecated
    - interfacer # deprecated
    - scopelint # deprecated
    - golint # deprecated
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - cyclop # duplicate of gocyclo
    - lll
    - dupl
    - wsl
    - nlreturn
    - gomnd
    - goerr113
    - wrapcheck
    - exhaustive
    - exhaustivestruct
    - testpackage
    - tparallel
    - paralleltest
    - prealloc
    - ifshort
    - forcetypeassert
    - bodyclose # Too many false positives: https://github.com/timakin/bodyclose/issues/30
    - nestif
    - gochecknoglobals
    - errname
    - nakedret
    - gocognit

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude:
    - 'ST1000: at least one file in a package should have a package comment'
    - 'G204: Subprocess launched with variable'
    - 'G304: Potential file inclusion via variable'
    - 'exported: exported (.*) be unexported'
    - 'exported: comment on exported (.*)'
    - 'ST1020: comment on exported (.*)'

  exclude-rules:
    - path: hpack.go
      text:  'SA6002: argument should be pointer-like to avoid allocations'
    - path: hpack.go
      text: 'ifElseChain: rewrite if-else to switch statement'
    - path: server.go
      text: 'SA9003: empty branch'
    - path: server.go
      text: 'appendAssign: append result not assigned to the same slice'
    - path: http2utils/utils.go
      text: 'G103: Use of unsafe calls should be audited'
    - path: server.go
      text: 'cyclomatic complexity 34 of func'
